set script_dir [file dirname [file normalize [info script]]]
set repo_root [file normalize [file join $script_dir .. ..]]
add_files -norecurse [glob -nocomplain [file join $repo_root rtl * *.sv]]
add_files -fileset sim_1 -norecurse [glob -nocomplain [file join $repo_root tb * *.sv]]
add_files -fileset constrs_1 -norecurse [glob -nocomplain [file join $repo_root vivado constraints *.xdc]]
set_property top $TOP_MODULE [current_fileset]
set_property top int8_mac_tb [get_filesets sim_1]
